[mgr]
sort_dir_first = true
sort_by = "natural"
show_hidden = false

[opener]
open = [{ run = 'open "$@"', desc = "Open with default app", for = "macos" }]
reveal = [{ run = 'open -R "$1"', desc = "Reveal in Finder", for = "macos" }]
browser = [{ run = 'open "$@"', desc = "Open in browser", for = "macos" }]
acrobat = [
  { run = 'open -a "Adobe Acrobat" "$@"', desc = "Open with Adobe Acrobat", for = "macos" },
]
kicad = [
  { run = 'open -a "KiCad" "$@"', desc = "Open with KiCad", for = "macos" },
]
bambustudio = [
  { run = 'open -a "BambuStudio" "$@"', desc = "Open with Bambu Studio", for = "macos" },
]
freecad = [
  { run = 'open -a "FreeCAD" "$@"', desc = "Open with FreeCAD", for = "macos" },
]

[[open.prepend_rules]]
url = "*.{html,htm}"
use = ["edit", "browser", "reveal"]

[[open.prepend_rules]]
url = "*.{xlsx,xls,xlsm,xltx,numbers,csv}"
use = ["open", "reveal"]

[[open.prepend_rules]]
url = "*.{docx,doc,docm,dotx,pages}"
use = ["open", "reveal"]

[[open.prepend_rules]]
url = "*.{pptx,ppt,pptm,potx,key}"
use = ["open", "reveal"]

[[open.prepend_rules]]
mime = "application/pdf"
use = ["acrobat", "reveal"]

[[open.prepend_rules]]
url = "*.{kicad_pcb,kicad_pro,kicad_sch}"
use = ["kicad", "reveal"]

[[open.prepend_rules]]
url = "*.{3mf,stl,step,stp}"
use = ["bambustudio", "reveal"]

[[open.prepend_rules]]
url = "*.{FCStd,fcstd}"
use = ["freecad", "reveal"]

[[open.prepend_rules]]
mime = "image/*"
use = ["open", "reveal"]

[[open.prepend_rules]]
mime = "video/*"
use = ["open", "reveal"]

[[open.prepend_rules]]
mime = "audio/*"
use = ["open", "reveal"]

[[plugin.prepend_fetchers]]
id = "git"
url = "*"
run = "git"
group = "git"

[[plugin.prepend_fetchers]]
id = "git"
url = "*/"
run = "git"
group = "git"

[[plugin.prepend_previewers]]
url = "*/"
run = "eza-preview"

[[plugin.prepend_previewers]]
mime = "image/tiff"
run = "magick"
